### ISSUE TITLE
Cursor

### ISSUE THREAD

**Issue by phodye** [RFCE2209-Velaryon/rfe2209-fec#64]
For the clickable text elements the cursor changes over to the default text select, might consider changing the css styling to cursor: grab;

https://github.com/RFCE2209-Velaryon/rfe2209-fec/blob/73702b3868c0c902961abbd30ebad0a6de557091/src/components/Q%26A/Questions.jsx#L61-L64

**Comment by dchong1999** [comment]
implemented changes so cursor changes to a pointer when over clickable text elements.
