### ISSUE TITLE
UI Suggestion for Related Product Widget

### ISSUE THREAD

**Issue by leiliangmichelle** [RFCE2209-Velaryon/rfe2209-fec#66]
Overall, great work, I am super impressed. 
I like your initial state <div>loading...</div> setup when the web page first loads.
Below is my UI suggestion for you.

I noticed that there are some black space around image for each of your related product card. 

https://github.com/RFCE2209-Velaryon/rfe2209-fec/blob/73702b3868c0c902961abbd30ebad0a6de557091/src/components/relateANDcompare/relatedCard.jsx#L46-L48

This might be the different sizes of product image retrieved from the API that caused this issue but I suggest you to look into setting images as a background to deal with different sizes of images. 

Once again, excellent work, keep it up!

**Comment by fuller2580** [comment]
implemented
