### ISSUE TITLE
OutfitList Suggestion for Related Product Widget

### ISSUE THREAD

**Issue by leiliangmichelle** [RFCE2209-Velaryon/rfe2209-fec#67]
When a new outfit gets added to the outfit list, as the size grows bigger, the 'add-to-outfit' card disappears from the list, which makes it hard to add more outfits.

https://github.com/RFCE2209-Velaryon/rfe2209-fec/blob/73702b3868c0c902961abbd30ebad0a6de557091/src/components/relateANDcompare/relatedCard.jsx#L46-L48

I suggest to look into how to fix 'add-to-outfit' card to be the first component on the list. 

Thanks

**Comment by fuller2580** [comment]
add to out card now stays at front of outfit list
