### ISSUE TITLE
Maybe put a ! operator in a boolean set state? 

### ISSUE THREAD

**Issue by phodye** [RFCE2209-Velaryon/rfe2209-fec#68]
https://github.com/RFCE2209-Velaryon/rfe2209-fec/blob/73702b3868c0c902961abbd30ebad0a6de557091/src/components/Q%26A/qna.jsx#L131

**Comment by dchong1999** [comment]
I tried this change but it broke my close button in my add question modal. I think this is because setQModal is being called in both qna.jsx and QuestionModal.jsx and the state has to be true/false at specific places so the toggle doesn't work all the time.
